"""cria todas as tabelas

Revision ID: 773d716f95e8
Revises: 
Create Date: 2025-06-18 17:24:25.980081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '773d716f95e8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('telefone_emergencia', sa.String(), nullable=True),
    sa.Column('senha', sa.String(), nullable=True),
    sa.Column('genero', sa.String(), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('tipo_usuario', sa.Enum('CONTRATANTE', 'CUIDADOR', name='tipousuario'), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index(op.f('ix_usuario_cpf'), 'usuario', ['cpf'], unique=True)
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    
    op.create_table('contratante',
    sa.Column('id_contratante', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_contratante'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_contratante')
    )
    
    op.create_table('cuidador',
    sa.Column('id_cuidador', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_cuidador'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_cuidador')
    )
    
    op.create_table('endereco',
    sa.Column('id_endereco', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('endereco', sa.String(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('complemento', sa.String(), nullable=True),
    sa.Column('bairro', sa.String(), nullable=False),
    sa.Column('cidade', sa.String(), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('referencia', sa.String(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_endereco')
    )
    
    op.create_table('hobbies',
    sa.Column('id_hobbie', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('atividades_gosta', sa.String(), nullable=False),
    sa.Column('pratica_esporte', sa.String(length=3), nullable=False),
    sa.Column('esporte_praticado', sa.String(), nullable=False),
    sa.Column('atividades_manuais', sa.String(length=3), nullable=False),
    sa.Column('atividades_manuais_praticadas', sa.String(), nullable=False),
    sa.Column('interesse_aprender', sa.String(length=3), nullable=False),
    sa.Column('interesse_aprender_especifico', sa.String(), nullable=False),
    sa.Column('gerenero_musical', sa.String(), nullable=False),
    sa.Column('filmes_tv', sa.String(), nullable=False),
    sa.Column('participa_eventos', sa.String(length=3), nullable=False),
    sa.Column('eventos', sa.String(), nullable=False),
    sa.Column('ensina', sa.String(length=3), nullable=False),
    sa.Column('ensinamentos_passados', sa.String(), nullable=False),
    sa.Column('atividades_tecnologicas', sa.String(length=3), nullable=False),
    sa.Column('atividades_tecnologicas_praticadas', sa.String(), nullable=False),
    sa.Column('outros_hobbies', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_hobbie')
    )
    
    op.create_table('questionario_contratante',
    sa.Column('id_questionario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('possui_condicao_medica', sa.String(length=3), nullable=False),
    sa.Column('condicao_medica', sa.String(), nullable=False),
    sa.Column('toma_medicamento', sa.String(length=3), nullable=False),
    sa.Column('medicamento', sa.String(), nullable=False),
    sa.Column('realiza_atividades_diarias', sa.String(length=3), nullable=False),
    sa.Column('atividades_diarias_ajuda', sa.String(), nullable=False),
    sa.Column('familia_apoio', sa.String(length=3), nullable=False),
    sa.Column('frequencia_visitas', sa.String(), nullable=False),
    sa.Column('principais_qualidades_preferencias', sa.String(), nullable=True),
    sa.Column('espera_cuidador', sa.String(), nullable=False),
    sa.Column('possui_deficiencias', sa.String(length=3), nullable=False),
    sa.Column('deficiencias', sa.String(), nullable=False),
    sa.Column('observacoes', sa.String(), nullable=True),
    sa.Column('id_contratante', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_contratante'], ['contratante.id_contratante'], ),
    sa.PrimaryKeyConstraint('id_questionario')
    )
    
    op.create_table('questionario_cuidador',
    sa.Column('id_questionario_cuidador', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cursos_realizados', sa.String(), nullable=True),
    sa.Column('instituicao_ensino', sa.String(), nullable=True),
    sa.Column('area_formacao', sa.String(), nullable=True),
    sa.Column('tempo_experiencia', sa.String(), nullable=True),
    sa.Column('responsabilidade_cuidado', sa.String(), nullable=True),
    sa.Column('possui_certificacao', sa.String(length=3), nullable=False),
    sa.Column('certificacoes', sa.String(), nullable=True),
    sa.Column('qualidades_preferencias', sa.String(), nullable=True),
    sa.Column('horario_disponivel', sa.String(), nullable=True),
    sa.Column('disponibilidade_plantao', sa.String(length=3), nullable=False),
    sa.Column('qualificacoes_cuidador', sa.String(), nullable=True),
    sa.Column('referencia_cuidador', sa.String(), nullable=True),
    sa.Column('id_cuidador', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_cuidador'], ['cuidador.id_cuidador'], ),
    sa.PrimaryKeyConstraint('id_questionario_cuidador')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questionario_cuidador')
    op.drop_table('questionario_contratante')
    op.drop_table('hobbies')
    op.drop_table('endereco')
    op.drop_table('cuidador')
    op.drop_table('contratante')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_cpf'), table_name='usuario')
    op.drop_table('usuario')
    # ### end Alembic commands ###
